import fs from 'fs'
import { Config } from 'orval'

const config: Config = {
  api: {
    input: {
      target: './data/QuantConnect-Platform-2.0.0.yaml',
    },
    output: {
      client: 'zod',
      mode: 'single',
      target: './src/index.ts',
      override: {
        useDates: true,
        zod: {
          generate: { param: false, query: false, header: false, body: true, response: true },
          coerce: {
            response: ['number', 'date'],
          },
        },
        header: () => ['eslint-disable max-len', 'This file is auto-generated by Orval. Do not edit.'],
      },
      prettier: true,
    },
    hooks: {
      afterAllFilesWrite: () => {
        const filePath = './src/index.ts'
        const fileContent = fs.readFileSync(filePath, 'utf-8')
        const patchedContent = fileContent.split('.optional()').join('.optional().nullable()')
        fs.writeFileSync(filePath, patchedContent, 'utf-8')
      },
    },
  },
}

export default config
